---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: false # Disable if your role does not rely on facts
  pre_tasks:
    - name: Gather Facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "env"
  roles:
    - name: Install yay
      role: finaldes.arch_setup.yay
