---
# SPDX-License-Identifier: Apache-2.0
namespace: finaldes
name: arch_setup
version: 1.0.0
dependencies:
  community.general: ">=12.6.0"
readme: README.md
authors:
  - Alex Alonso <alex4551@gmail.com>

description: Automated Arch Linux setup and configuration collection.

# Change to Apache-2.0
license:
  - Apache-2.0

# Leave license_file empty as you are using the 'license' list above
license_file: ""

# Add relevant tags for searchability on Galaxy
tags:
  - arch
  - linux
  - bootstrap

# Update these with your real repository links
repository: https://github.com/finaldes/ansible-arch-setup
documentation: https://github.com/finaldes/ansible-arch-setup/wiki
homepage: https://github.com/finaldes/ansible-arch-setup
issues: https://github.com/finaldes/ansible-arch-setup/issues
