[project]
name = "arch-setup"
version = "0.1.0"
description = "Automated Arch Linux setup and configuration collection."
authors = [{ name = "Alex Alonso", email = "alex4551@gmail.com" }]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["ansible-core>=2.21.1", "ansible-lint>=26.6.0"]
[project.urls]
Homepage = "https://github.com/finaldes/ansible-arch-setup"
Repository = "https://github.com/finaldes/ansible-arch-setup"
Issues = "https://github.com/finaldes/ansible-arch-setup/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
