---
# tasks file for zsh_setup
- name: Pacman update
  community.general.pacman:
    update_cache: true
  become: true
- name: Install chezmoi
  community.general.pacman:
    name: chezmoi
    state: latest
  become: true
  when: dev_setup_install_chezmoi
- name: Install stow
  community.general.pacman:
    name: stow
    state: latest
  become: true
  when: dev_setup_install_stow
- name: Install dev tool using pacman
  community.general.pacman:
    name:
      - actionlint
      - bat
      - bat-extras
      - eza
      - fzf
      - fd
      - glow
      - helix
      - just
      - tree
    state: latest
  become: true
