---
# tasks file for roles/ssh
- name: Install openssh
  community.general.pacman:
    name: openssh
    state: present

- name: Ensure sshd is running and enabled
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
