---
- name: Change user login shell to Zsh
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh
  become: true
- name: Copy dotfiles file
  vars:
    dotfiles_list:
      - src: .zshrc
        dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_id'] }}"
      - src: .p10k.zsh
        dest: "{{ ansible_facts['env']['HOME'] }}/.p10k.zsh"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_id'] }}"
  block:
    - name: Ensure target parent directories exist
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0755"
      loop: "{{ dotfiles_list }}"

    - name: Copy dotfiles file
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0644"
      loop: "{{ dotfiles_list }}"

  # This stores your list once so both tasks can use it cleanly
