---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: false # Disable if your role does not rely on facts
  vars:
    git_name: "{{ lookup('env', 'GIT_NAME') | default('Test', true) }}"
    git_email: "{{ lookup('env', 'GIT_EMAIL') | default('test@test.local', true) }}"
    git_signingkey: "{{ lookup('env', 'GIT_SINGNING_KEY') | default('test@test.local', true) }}"
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "user"
          - "env"
          # - "distribution"
    - name: Configure sudoers
      community.general.sudoers:
        name: 99_ansible
        user: "{{ ansible_facts['user_id'] }}"
        commands: ALL
        nopassword: true
      become: true
  roles:
    - name: Install git
      role: finaldes.arch_setup.git
    - name: yay install
      role: finaldes.arch_setup.yay
      yay_pre_compile: true
    - name: Setup Dev Server
      role: finaldes.arch_setup.dev_setup
    - name: Setup zsh
      role: finaldes.arch_setup.zsh
      zsh_install_p10k_font: false
