- name: Install docker on debian
  ansible.builtin.include_tasks: debian_install.yml
  when: ansible_facts['os_family'] in ['Debian']
- name: Install docker on Arch linux
  community.general.pacman:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: latest
  become: true
  when:
    - ansible_facts['os_family'] in ['Archlinux']
    - docker_release_channel == 'stable'
- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true
  become: true
  when: docker_add_user_to_group | bool
- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
